from __future__ import annotations

import hashlib
from dataclasses import dataclass
from pathlib import Path

from .iterm_profile import dumps_document
from .presets import apply_preset_to_profile_dict, get_preset
from .safe_io import atomic_write_text, backup_file

DEFAULT_DYNAMIC_PROFILES_DIR = (
    Path.home() / "Library" / "Application Support" / "iTerm2" / "DynamicProfiles"
)
DEFAULT_AUTOLAUNCH_DIR = (
    Path.home() / "Library" / "Application Support" / "iTerm2" / "Scripts" / "AutoLaunch"
)
# App-local state directory — used to record per-session state (e.g. previous-default GUID).
DEFAULT_APP_STATE_DIR = Path.home() / "Library" / "Application Support" / "term-chameleon"
AUTOLAUNCH_FILENAME = "term_chameleon_default_profile.py"

# Backups of files inside iTerm2-scanned directories (DynamicProfiles, AutoLaunch) must
# NOT stay in those directories — iTerm2 tries to load every file it finds there.
# DynamicProfiles loads .json files; AutoLaunch runs every file, including stray .backup.*
# files, and triggers an error dialog.  Route backups to a dedicated app-state subdir,
# mirroring the pattern in watch_daemon.py (SCRIPT_BACKUP_DIR).
PROFILE_BACKUP_DIR = DEFAULT_APP_STATE_DIR / "profile-backups"
AUTOLAUNCH_BACKUP_DIR = DEFAULT_APP_STATE_DIR / "autolaunch-backups"


def _guid_for_name(name: str) -> str:
    """Derive a stable, unique GUID from a profile name via truncated SHA-1.

    Two distinct names always produce distinct GUIDs; the same name always
    produces the same GUID across installs, making installs idempotent in
    iTerm2's profile registry (which keys profiles by GUID).
    """
    digest = hashlib.sha1(name.encode("utf-8"), usedforsecurity=False).hexdigest()[:16].upper()
    return f"TERM-CHAMELEON-{digest}"


def profile_document(
    *, name: str = "Adaptive Glass", guid: str | None = None, preset_name: str = "balanced"
) -> dict:
    # Derive a stable GUID from the profile name so that two installs with
    # different --name values do not collide in iTerm2's GUID-keyed registry.
    resolved_guid = guid or _guid_for_name(name)
    profile = {
        "Name": name,
        "Guid": resolved_guid,
        "Dynamic Profile Parent Name": "Default",
    }
    apply_preset_to_profile_dict(profile, get_preset(preset_name))
    return {"Profiles": [profile]}


def balanced_profile_document(name: str = "Adaptive Glass", guid: str | None = None) -> dict:
    return profile_document(name=name, guid=guid, preset_name="balanced")


def install_profile(
    *,
    target_dir: Path = DEFAULT_DYNAMIC_PROFILES_DIR,
    name: str = "Adaptive Glass",
    preset_name: str = "balanced",
    filename: str = "term-chameleon-adaptive-glass.json",
    dry_run: bool = False,
) -> tuple[Path, str]:
    document = profile_document(name=name, preset_name=preset_name)
    content = dumps_document(document)
    target = target_dir / filename
    if not dry_run:
        target_dir.mkdir(parents=True, exist_ok=True)
        if target.exists():
            existing = target.read_text(encoding="utf-8")
            if existing != content:
                backup_file(target, dest_dir=PROFILE_BACKUP_DIR)
                atomic_write_text(target, content)
            # Byte-identical content: skip backup and write (idempotent re-install).
        else:
            atomic_write_text(target, content)
    return target, content


def install_balanced_profile(
    *,
    target_dir: Path = DEFAULT_DYNAMIC_PROFILES_DIR,
    name: str = "Adaptive Glass",
    filename: str = "term-chameleon-adaptive-glass.json",
    dry_run: bool = False,
) -> tuple[Path, str]:
    return install_profile(
        target_dir=target_dir,
        name=name,
        preset_name="balanced",
        filename=filename,
        dry_run=dry_run,
    )


def autolaunch_script(
    profile_name: str = "Adaptive Glass",
    *,
    app_state_dir: Path = DEFAULT_APP_STATE_DIR,
) -> str:
    # The previous-default GUID file lets `uninstall` restore the prior default.
    # NOTE: make-default is NOT automatically reversed — it persists in iTerm2
    # preferences even after the AutoLaunch script is removed.  Run
    # `term-chameleon uninstall` to remove the script and receive guidance on
    # restoring the prior default via iTerm2 Preferences > Profiles.
    prev_guid_file = str(app_state_dir / "previous-default-guid.txt")
    return f'''#!/usr/bin/env python3
"""Auto-generated by Term Chameleon.

Makes the Term Chameleon iTerm2 Dynamic Profile the default profile after
Dynamic Profiles are loaded.  It is intentionally small and idempotent.

Before setting the new default it persists the current default profile GUID
to {prev_guid_file!r} so that `term-chameleon uninstall` can report
what the previous default was.  The default-profile change itself is NOT
automatically reversed on uninstall — use iTerm2 Preferences > Profiles to
select your preferred default after removing this script.
"""

import iterm2
import os
import pathlib

PROFILE_NAME = {profile_name!r}
PREV_GUID_FILE = pathlib.Path({prev_guid_file!r})


async def main(connection):
    profiles = await iterm2.PartialProfile.async_query(connection)
    # Capture current default GUID before overriding it (best-effort).
    for profile in profiles:
        if profile.is_default:
            try:
                PREV_GUID_FILE.parent.mkdir(parents=True, exist_ok=True)
                if not PREV_GUID_FILE.exists():
                    PREV_GUID_FILE.write_text(profile.guid or "", encoding="utf-8")
            except OSError:
                pass
            break
    for profile in profiles:
        if profile.name == PROFILE_NAME:
            await profile.async_make_default()
            return
    print(f"Term Chameleon profile not found: {{PROFILE_NAME}}")


iterm2.run_until_complete(main)
'''


def install_autolaunch_script(
    *,
    target_dir: Path = DEFAULT_AUTOLAUNCH_DIR,
    profile_name: str = "Adaptive Glass",
    app_state_dir: Path = DEFAULT_APP_STATE_DIR,
    dry_run: bool = False,
) -> tuple[Path, str]:
    content = autolaunch_script(profile_name, app_state_dir=app_state_dir)
    target = target_dir / AUTOLAUNCH_FILENAME
    if not dry_run:
        target_dir.mkdir(parents=True, exist_ok=True)
        if target.exists():
            existing = target.read_text(encoding="utf-8")
            if existing != content:
                backup_file(target, dest_dir=AUTOLAUNCH_BACKUP_DIR)
                atomic_write_text(target, content)
            # Byte-identical content: skip backup and write (idempotent re-install).
        else:
            atomic_write_text(target, content)
        target.chmod(0o755)
    return target, content


@dataclass(frozen=True)
class ProfileUninstall:
    """Result of :func:`uninstall_profile`."""

    profile_target: Path
    autolaunch_target: Path
    profile_removed: bool
    autolaunch_removed: bool
    profile_backup_path: Path | None
    autolaunch_backup_path: Path | None
    # GUID of the previous default profile, if recorded by the AutoLaunch script.
    previous_default_guid: str | None


def uninstall_profile(
    *,
    target_dir: Path = DEFAULT_DYNAMIC_PROFILES_DIR,
    autolaunch_dir: Path = DEFAULT_AUTOLAUNCH_DIR,
    app_state_dir: Path = DEFAULT_APP_STATE_DIR,
    filename: str = "term-chameleon-adaptive-glass.json",
    dry_run: bool = False,
    backup: bool = True,
) -> ProfileUninstall:
    """Remove the installed Dynamic Profile JSON and the make-default AutoLaunch script.

    Mirrors :func:`~term_chameleon.watch_daemon.uninstall_watch_autolaunch_script`.
    Handles never-installed and partially-installed states gracefully (no error
    if a target does not exist).

    The make-default change itself is NOT automatically reversed — iTerm2
    stores the default profile in its own preferences.  The caller should
    display the ``previous_default_guid`` (if available) so the user knows
    which profile to re-select in iTerm2 Preferences > Profiles.
    """
    profile_target = target_dir.expanduser() / filename
    autolaunch_target = autolaunch_dir.expanduser() / AUTOLAUNCH_FILENAME

    profile_backup: Path | None = None
    autolaunch_backup: Path | None = None

    profile_removed = profile_target.exists()
    if profile_removed and not dry_run:
        if backup:
            profile_backup = backup_file(profile_target, dest_dir=PROFILE_BACKUP_DIR)
        profile_target.unlink()

    autolaunch_removed = autolaunch_target.exists()
    if autolaunch_removed and not dry_run:
        if backup:
            autolaunch_backup = backup_file(autolaunch_target, dest_dir=AUTOLAUNCH_BACKUP_DIR)
        autolaunch_target.unlink()

    # Read the persisted previous-default GUID recorded by the AutoLaunch script.
    prev_guid_file = app_state_dir.expanduser() / "previous-default-guid.txt"
    previous_default_guid: str | None = None
    try:
        raw = prev_guid_file.read_text(encoding="utf-8").strip()
        previous_default_guid = raw if raw else None
    except OSError:
        pass

    return ProfileUninstall(
        profile_target=profile_target,
        autolaunch_target=autolaunch_target,
        profile_removed=profile_removed,
        autolaunch_removed=autolaunch_removed,
        profile_backup_path=profile_backup,
        autolaunch_backup_path=autolaunch_backup,
        previous_default_guid=previous_default_guid,
    )
