from __future__ import annotations

from pathlib import Path

from .iterm_profile import dumps_document
from .presets import apply_preset_to_profile_dict, get_preset

DEFAULT_DYNAMIC_PROFILES_DIR = (
    Path.home() / "Library" / "Application Support" / "iTerm2" / "DynamicProfiles"
)
DEFAULT_AUTOLAUNCH_DIR = (
    Path.home() / "Library" / "Application Support" / "iTerm2" / "Scripts" / "AutoLaunch"
)
AUTOLAUNCH_FILENAME = "term_chameleon_default_profile.py"


def profile_document(
    *, name: str = "Adaptive Glass", guid: str | None = None, preset_name: str = "balanced"
) -> dict:
    guid = guid or "TERM-CHAMELEON-ADAPTIVE-GLASS"
    profile = {
        "Name": name,
        "Guid": guid,
        "Dynamic Profile Parent Name": "Default",
    }
    apply_preset_to_profile_dict(profile, get_preset(preset_name))
    return {"Profiles": [profile]}


def balanced_profile_document(name: str = "Adaptive Glass", guid: str | None = None) -> dict:
    return profile_document(name=name, guid=guid, preset_name="balanced")


def install_profile(
    *,
    target_dir: Path = DEFAULT_DYNAMIC_PROFILES_DIR,
    name: str = "Adaptive Glass",
    preset_name: str = "balanced",
    filename: str = "term-chameleon-adaptive-glass.json",
    dry_run: bool = False,
) -> tuple[Path, str]:
    document = profile_document(name=name, preset_name=preset_name)
    content = dumps_document(document)
    target = target_dir / filename
    if not dry_run:
        target_dir.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
    return target, content


def install_balanced_profile(
    *,
    target_dir: Path = DEFAULT_DYNAMIC_PROFILES_DIR,
    name: str = "Adaptive Glass",
    filename: str = "term-chameleon-adaptive-glass.json",
    dry_run: bool = False,
) -> tuple[Path, str]:
    return install_profile(
        target_dir=target_dir,
        name=name,
        preset_name="balanced",
        filename=filename,
        dry_run=dry_run,
    )


def autolaunch_script(profile_name: str = "Adaptive Glass") -> str:
    return f'''#!/usr/bin/env python3
"""Auto-generated by Term Chameleon.

Makes the Term Chameleon iTerm2 Dynamic Profile the default profile after
Dynamic Profiles are loaded. It is intentionally small and idempotent.
"""

import iterm2

PROFILE_NAME = {profile_name!r}


async def main(connection):
    profiles = await iterm2.PartialProfile.async_query(connection)
    for profile in profiles:
        if profile.name == PROFILE_NAME:
            await profile.async_make_default()
            return
    print(f"Term Chameleon profile not found: {{PROFILE_NAME}}")


iterm2.run_until_complete(main)
'''


def install_autolaunch_script(
    *,
    target_dir: Path = DEFAULT_AUTOLAUNCH_DIR,
    profile_name: str = "Adaptive Glass",
    dry_run: bool = False,
) -> tuple[Path, str]:
    content = autolaunch_script(profile_name)
    target = target_dir / AUTOLAUNCH_FILENAME
    if not dry_run:
        target_dir.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        target.chmod(0o755)
    return target, content
