from __future__ import annotations

import os
import shlex
import sys
from dataclasses import dataclass
from pathlib import Path

from .install import DEFAULT_AUTOLAUNCH_DIR
from .safe_io import atomic_write_text, backup_file


class InvalidExecutableError(ValueError):
    """Raised when a user-supplied executable path fails validation."""

    pass


WATCH_AUTOLAUNCH_FILENAME = "term_chameleon_watch_live.py"
DEFAULT_LOG_PATH = Path.home() / "Library" / "Logs" / "term-chameleon-watch-live.log"
DEFAULT_PID_PATH = (
    Path.home() / "Library" / "Application Support" / "term-chameleon" / "watch-live.pid"
)


@dataclass(frozen=True)
class WatchDaemonInstall:
    target: Path
    content: str
    command: tuple[str, ...]
    log_path: Path
    pid_path: Path


@dataclass(frozen=True)
class WatchDaemonStatus:
    target: Path
    installed: bool
    executable: bool
    log_path: Path
    log_exists: bool
    pid_path: Path
    pid: int | None
    running: bool

    @property
    def healthy(self) -> bool:
        return self.installed and self.executable


@dataclass(frozen=True)
class WatchDaemonUninstall:
    target: Path
    removed: bool
    backup_path: Path | None


def pid_is_running(pid: int) -> bool:
    if pid <= 0:
        # os.kill(0, 0) targets the process group; os.kill(-1, 0) targets all
        # processes the user may signal.  Both would return True spuriously, so
        # reject non-positive PIDs as not-running.
        return False
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    return True


def read_pid(path: Path) -> int | None:
    try:
        pid = int(path.expanduser().read_text(encoding="utf-8").strip())
    except (FileNotFoundError, ValueError):
        return None
    if pid <= 0:
        return None
    return pid


def validate_executable(executable: str) -> None:
    """Validate a user-supplied executable path before subprocess execution.

    Args:
        executable: The executable path to validate.

    Raises:
        InvalidExecutableError: If the executable path is invalid or unsafe.
    """
    if not executable:
        raise InvalidExecutableError("Executable path cannot be empty")

    if any(char in executable for char in (";", "|", "&", "$", "`", "\n", "\r")):
        raise InvalidExecutableError("Executable path contains shell metacharacters (disallowed)")

    expanded = Path(executable).expanduser()

    if not expanded.exists():
        raise InvalidExecutableError(f"Executable path does not exist: {executable}")

    if not expanded.is_file():
        raise InvalidExecutableError(f"Executable path is not a file: {executable}")

    if not os.access(expanded, os.X_OK):
        raise InvalidExecutableError(f"Executable path is not executable: {executable}")


def watch_live_command(
    *,
    executable: str | None = None,
    interval: float = 10.0,
    stable: int = 3,
    cooldown: float = 10.0,
    output_dir: Path = Path("~/Library/Logs/term-chameleon/watch-live-artifacts"),
    initial_mode: str = "balanced",
    iterm_window: bool = False,
    region: str | None = None,
) -> tuple[str, ...]:
    resolved_executable = executable or sys.executable

    if executable is not None:
        validate_executable(executable)

    command = [
        resolved_executable,
        "-m",
        "term_chameleon.cli",
        "watch-live",
        "--yes",
        "--duration",
        "315360000",
        "--interval",
        str(interval),
        "--stable",
        str(stable),
        "--cooldown",
        str(cooldown),
        "--output-dir",
        str(output_dir.expanduser()),
        "--initial-mode",
        initial_mode,
    ]
    if region is not None:
        command.extend(["--region", region])
    elif iterm_window:
        command.append("--iterm-window")
    return tuple(command)


def watch_autolaunch_script(
    *,
    command: tuple[str, ...],
    log_path: Path = DEFAULT_LOG_PATH,
    pid_path: Path = DEFAULT_PID_PATH,
) -> str:
    command_literal = repr(list(command))
    return f'''#!/usr/bin/env python3
"""Auto-generated by Term Chameleon.

Starts one background `term-chameleon watch-live --yes` process when iTerm2
launches. The watcher mutates only the current iTerm2 session-local profile.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

COMMAND = {command_literal}
LOG_PATH = Path({str(log_path)!r}).expanduser()
PID_PATH = Path({str(pid_path)!r}).expanduser()


def _pid_is_running(pid: int) -> bool:
    if pid <= 0:
        # os.kill(0, 0) / os.kill(-1, 0) would succeed spuriously.
        return False
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    return True


def _existing_watcher_running() -> bool:
    try:
        pid = int(PID_PATH.read_text().strip())
    except (FileNotFoundError, ValueError):
        return False
    if pid <= 0:
        return False
    return _pid_is_running(pid)


def main() -> None:
    if _existing_watcher_running():
        return
    LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    PID_PATH.parent.mkdir(parents=True, exist_ok=True)
    # Pass the PID path to the child via environment variable so the
    # watch-live process writes its own PID and removes it on exit.
    # This prevents stale PID files when the watcher is killed or crashes.
    env = os.environ.copy()
    env["TC_WATCH_PID_PATH"] = str(PID_PATH)
    with LOG_PATH.open("ab", buffering=0) as log:
        subprocess.Popen(
            COMMAND,
            stdout=log,
            stderr=subprocess.STDOUT,
            start_new_session=True,
            env=env,
        )


if __name__ == "__main__":
    main()
'''


def install_watch_autolaunch_script(
    *,
    target_dir: Path = DEFAULT_AUTOLAUNCH_DIR,
    command: tuple[str, ...],
    log_path: Path = DEFAULT_LOG_PATH,
    pid_path: Path = DEFAULT_PID_PATH,
    dry_run: bool = False,
) -> WatchDaemonInstall:
    content = watch_autolaunch_script(command=command, log_path=log_path, pid_path=pid_path)
    target = target_dir.expanduser() / WATCH_AUTOLAUNCH_FILENAME
    if not dry_run:
        target.parent.mkdir(parents=True, exist_ok=True)
        if target.exists():
            backup_file(target)
        atomic_write_text(target, content)
        target.chmod(0o755)
    return WatchDaemonInstall(
        target=target,
        content=content,
        command=command,
        log_path=log_path.expanduser(),
        pid_path=pid_path.expanduser(),
    )


def get_watch_daemon_status(
    *,
    target_dir: Path = DEFAULT_AUTOLAUNCH_DIR,
    log_path: Path = DEFAULT_LOG_PATH,
    pid_path: Path = DEFAULT_PID_PATH,
) -> WatchDaemonStatus:
    target = target_dir.expanduser() / WATCH_AUTOLAUNCH_FILENAME
    resolved_log_path = log_path.expanduser()
    resolved_pid_path = pid_path.expanduser()
    pid = read_pid(resolved_pid_path)
    return WatchDaemonStatus(
        target=target,
        installed=target.exists(),
        executable=target.exists() and os.access(target, os.X_OK),
        log_path=resolved_log_path,
        log_exists=resolved_log_path.exists(),
        pid_path=resolved_pid_path,
        pid=pid,
        running=pid_is_running(pid) if pid is not None else False,
    )


def uninstall_watch_autolaunch_script(
    *,
    target_dir: Path = DEFAULT_AUTOLAUNCH_DIR,
    dry_run: bool = False,
    backup: bool = True,
) -> WatchDaemonUninstall:
    target = target_dir.expanduser() / WATCH_AUTOLAUNCH_FILENAME
    backup_path: Path | None = None
    removed = target.exists()
    if removed and not dry_run:
        if backup:
            backup_path = backup_file(target)
        target.unlink()
    return WatchDaemonUninstall(target=target, removed=removed, backup_path=backup_path)


def shell_command(command: tuple[str, ...]) -> str:
    return " ".join(shlex.quote(part) for part in command)
